kind: pipeline
type: kubernetes
name: default
service_account_name: default

steps:
  - name: build-latest-bastion
    image: registry.werf.io/werf/werf:1.2-stable
    pull: if-not-exists
    privileged: true
    user: 0
    group: 0
    environment:
      REGISTRY:
        from_secret: docker_hub_registry_url
      USERNAME:
        from_secret: docker_hub_username
      PASSWORD:
        from_secret: docker_hub_password
    commands:
      - werf cr login -u $USERNAME -p $PASSWORD $REGISTRY
      - werf build bastion --repo glendmaatita/bastion --add-custom-tag latest
    volumes:
      - name: cache
        path: /home/build/.werf
    when:
      branch:
        - main
  
  - name: build-latest-node
    image: registry.werf.io/werf/werf:1.2-stable
    pull: if-not-exists
    privileged: true
    user: 0
    group: 0
    environment:
      REGISTRY:
        from_secret: docker_hub_registry_url
      USERNAME:
        from_secret: docker_hub_username
      PASSWORD:
        from_secret: docker_hub_password
    commands:
      - werf cr login -u $USERNAME -p $PASSWORD $REGISTRY
      - werf build node --repo glendmaatita/node --add-custom-tag latest
    volumes:
      - name: cache
        path: /home/build/.werf
    when:
      branch:
        - main

  - name: build-latest-rust
    image: registry.werf.io/werf/werf:1.2-stable
    pull: if-not-exists
    privileged: true
    user: 0
    group: 0
    environment:
      REGISTRY:
        from_secret: docker_hub_registry_url
      USERNAME:
        from_secret: docker_hub_username
      PASSWORD:
        from_secret: docker_hub_password
    commands:
      - werf cr login -u $USERNAME -p $PASSWORD $REGISTRY
      - werf build rust --repo glendmaatita/rust --add-custom-tag latest
    volumes:
      - name: cache
        path: /home/build/.werf
    when:
      branch:
        - main

  - name: notification
    image: appleboy/drone-discord
    privileged: true
    user: 0
    group: 0
    depends_on:
      - build-latest-bastion
      - build-latest-node
      - build-latest-rust
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_secret
      username: DroneCI
      avatar_url: https://cdn.discordapp.com/attachments/892612412014997557/1153503922162511892/drone-ci.png
      message: >
        {{#success build.status}}
          Build **core** is *done*. Check on https://drone.dev.retrosuite.co/RetroSuite/bastion/{{build.number}} for more details.
        {{else}}
          Build **core** is *failed*. Check on https://drone.dev.retrosuite.co/RetroSuite/bastion/{{build.number}} for more details.
        {{/success}}

volumes:
  - name: cache
    claim:
      name: werf-cache-pvc
      read_only: false
