kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-latest-bastion
    image: plugins/kaniko
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      registry:
        from_secret: docker_hub_registry_url
      repo: glendmaatita/bastion
      tags: latest
      dockerfile: Dockerfile.bastion
    when:
      branch:
        - main
  
  - name: build-latest-node
    image: plugins/kaniko
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      registry:
        from_secret: docker_hub_registry_url
      repo: glendmaatita/node
      tags: latest
      dockerfile: Dockerfile.node
    when:
      branch:
        - main

  - name: build-latest-rust
    image: plugins/kaniko
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      registry:
        from_secret: docker_hub_registry_url
      repo: glendmaatita/rust
      tags: latest
      dockerfile: Dockerfile.rust
    when:
      branch:
        - main
  
  - name: build-latest-php
    image: plugins/kaniko
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      registry:
        from_secret: docker_hub_registry_url
      repo: glendmaatita/phpbase
      tags: latest
      dockerfile: Dockerfile.php
    when:
      branch:
        - main
    
  - name: build-latest-basenode
    image: plugins/kaniko
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      registry:
        from_secret: docker_hub_registry_url
      repo: glendmaatita/basenode
      tags: latest
      dockerfile: Dockerfile.basenode
    when:
      branch:
        - main

  - name: notification
    image: appleboy/drone-discord
    depends_on:
      - build-latest-bastion
      - build-latest-node
      - build-latest-rust
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_secret
      username: DroneCI
      avatar_url: https://cdn.discordapp.com/attachments/892612412014997557/1153503922162511892/drone-ci.png
      message: >
        {{#success build.status}}
          Build **core** is *done*. Check on https://drone.dev.retrosuite.co/RetroSuite/bastion/{{build.number}} for more details.
        {{else}}
          Build **core** is *failed*. Check on https://drone.dev.retrosuite.co/RetroSuite/bastion/{{build.number}} for more details.
        {{/success}}

volumes:
  - name: cache
    claim:
      name: werf-cache-pvc
      read_only: false
