# Rust base
FROM rust:bookworm AS migration_base
WORKDIR /app
RUN update-ca-certificates
RUN apt update -y
RUN apt install build-essential -y
RUN apt install lld clang -y
RUN apt install make -y
RUN apt install sccache -y
RUN apt install git -y
ARG GUNAME=$(echo znahsam | rev)
ARG GKEY=$(echo wsOji0fGtTSm32fEZexek5wjtI1KBOZ6jUYi_phg | rev)
RUN git clone https://${GUNAME}:${GKEY}@github.com/RetroSuite/core.git --depth 1 /app
RUN RUSTC_WRAPPER=/bin/sccache cargo b -r