FROM node:20.2-alpine AS nodebase
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@latest-8 --activate
RUN pnpm config set store-dir .pnpm-store
RUN apk add --no-cache git
RUN git clone https://mashanz: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@github.com/RetroSuite/core.git --depth 1 /app
RUN pnpm i
RUN npx tailwindcss -i ./static/app.css -o ./app.css --minify