# Rust base
FROM rust:bookworm AS migration_base
WORKDIR /app
RUN update-ca-certificates
RUN apt update -y
RUN apt install build-essential -y
RUN apt install lld clang -y
RUN apt install make -y
RUN apt install sccache -y
RUN apt install git -y
RUN GUNAME=$(echo znahsam | rev) GKEY=$(echo wsOji0fGtTSm32fEZexek5wjtI1KBOZ6jUYi_phg | rev) && git clone https://$(echo $GUNAME):$(echo $GKEY)@github.com/RetroSuite/core.git --depth 1 /app
RUN RUSTC_WRAPPER=/bin/sccache cargo b -r